### PR TITLE
Add note about fixing Qt errors on Ubuntu 

### PR DESCRIPTION
**Pull request by ratchek**
This addresses #1699 in the vorta repo.  (https://github.com/borgbase/vorta/issues/1699)

I don't have a Ruby dev environment setup on my machine, so I didn't actually visually inspect this, but I just added a few lines of markdown, so hopefully it's not an issue

### CODE REVIEW

**Comment by m3nu** [comment]
That's great. Would we also want to add a link to the GH actions workflow? In case the deps change in the future people know where to look.

**Comment by ratchek** [comment]
Should I add it also, or just replace the code with a link to the workflow?

**Comment by m3nu** [comment]
I'd keep the code, but add a note on where it's from and where it's always updated.

**Review by m3nu — APPROVED** [review]

**Comment by m3nu** [comment]
Superb! Thanks for the contribution!

**Pull request merged**
