### PR TITLE
Improve Linux install instructions

### PR DESCRIPTION
**Pull request by Thatoo**

### CODE REVIEW

**Comment by m3nu** [comment]
Thanks for the contribution, @Thatoo . Does it make sense to add this file when Vorta runs and it doesn't exist yet. More user-friendly than adding it manually.

Can you use this for the Debian package, @sten0?

**Comment by Hofer-Julian** [comment]
> Thanks for the contribution, @Thatoo . Does it make sense to add this file when Vorta runs and it doesn't exist yet. More user-friendly than adding it manually.

Not really, since this is now specific to a --user installation and to python3.7.
We could include in the installations instructions to copy (and maybe modifying) our already existing .desktop file [here](https://github.com/borgbase/vorta/blob/0b44d00f4753f4bcc2b71654197ac74d94e455d9/src/vorta/assets/metadata/com.borgbase.Vorta.desktop)

Regarding, debian: The already existing one should be used by debian. If there are changes necessary they should done there.

**Comment by m3nu** [comment]
We already have a .desktop file for the autostart feature. How about moving it to the assets folder as single file and linking to it from the docs instead?

https://github.com/borgbase/vorta/blob/1bb780897cfb655118caa1ce5bb09c28ee916887/src/vorta/autostart.py

**Comment by Hofer-Julian** [comment]
Like I mentioned above: we already have a .desktop files in our assets.
That we generate a second one for autostart is not unusual, nextcloud does the same.
I hope the autostart generation will become simpler in the future though as soon as autostart is natively supported by flatpak.

**Comment by m3nu** [comment]
> Like I mentioned above: we already have a .desktop files in our assets.
> That we generate a second one for autostart is not unusual, nextcloud does the same.

All fine. I just suggest:

- having just one .desktop file
- linking to it from the docs instead of duplicating it here
- you also need it for Flatpak?

**Comment by Hofer-Julian** [comment]
> > Like I mentioned above: we already have a .desktop files in our assets.
> > That we generate a second one for autostart is not unusual, nextcloud does the same.
> 
> All fine. I just suggest:
> 
>     * having just one .desktop file
> 
>     * linking to it from the docs instead of duplicating it here
> 
>     * you also need it for Flatpak?

I see your points, but wouldn't make this things more complicated?
There isn't the ONE place where pip would install vorta, so the docs would look something like this:
1. Find vorta
2. Find the .desktop file in vorta's dir tree
3. Modify it with the right executable and icon path
4. Copy it to the correct place

Regarding flatpak, yes it is required during building, afterwards everything is handled by flatpak (apart from the autostart at the moment).

I see that there is a need for @Thatoo Pull Request. We do not have debian package yet, and there are people who are strictly opposed using flatpaks.
For development purposes a .desktop file is not required, but for actually using it, it is nice, because it creates the entry in your start menu. I'd consider this a special case and explain the problematic, but only link to e.g. https://wiki.archlinux.org/index.php/Desktop_entries#Application_entry for the do-it-yourself-user

**Comment by m3nu** [comment]
I just imagine a link to Github, no need to look in the source code. With this PR, we would have 3x .desktop:

1. For Flatpak: https://github.com/borgbase/vorta/blob/a4436d8f248f9ba0541409b607295057ba6f3806/src/vorta/assets/metadata/com.borgbase.Vorta.desktop
2. For Autostart: https://github.com/borgbase/vorta/blob/1bb780897cfb655118caa1ce5bb09c28ee916887/src/vorta/autostart.py
3. For manual setup in the docs.

1 looks quite unique, so we leave it alone. 2 and 3 could be combined. `autostart.py` could read a file from assets and we link to it.

Benefits: Only 1 place to change when there is an improvement to the .desktop file.

I'm not talking about the proecess of installing the .desktop file here. Just where to keep it. The docs would say "Go to this file and remove the last 2 lines if you don't want autostart.

**Comment by Hofer-Julian** [comment]
> I just imagine a link to Github, no need to look in the source code. With this PR, we would have 3x .desktop:

Good point, didn't think of that.
> 
>     1. For Flatpak: https://github.com/borgbase/vorta/blob/a4436d8f248f9ba0541409b607295057ba6f3806/src/vorta/assets/metadata/com.borgbase.Vorta.desktop

Not only flatpak btw.
For every package including debian.


> 1 looks quite unique, so we leave it alone. 2 and 3 could be combined. `autostart.py` could read a file from assets and we link to it.

Actually, 1 and 3 are more similar :)
You place 2 in a certain place, the OS will look there and it will autostart, the two last lines are not the ones triggering the autostart.
1 and 3 give you an entry in the start menu.

If you want to do something automatic, I wouldn't do it in Vorta, but rather inside setup.py (like if os is linux and not flatpak then...).

However, currently my favourite solution would be to link to our desktop file on github (as you suggested) and tell people where to copy it, instead of writing code, which will probably never fit all use cases. It is still a niche use case, linux->no flatpak->no (debian) package->pip

**Comment by m3nu** [comment]
Made another version with a link at #9. Below how it looks. Input welcome, also from @Thatoo .

Screen Shot 2020-06-01 at 18 35 14

**Comment by Hofer-Julian** [comment]
I like it :)

**Comment by m3nu** [comment]
Merged via #9.

**Comment by sten0** [comment]
> Thanks for the contribution, @Thatoo . Does it make sense to add this file when Vorta runs and it doesn't exist yet. More user-friendly than adding it manually.
> 
> Can you use this for the Debian package, @sten0?

Yes, and I've already imported a snapshot that contains it.  From my perspective autostart should be enabled for all users by linking or copying the file to `/etc/xdg/autostart`, and for individual users by doing the same to `$HOME/.config/autostart`, or by using the Desktop's GUI to the equivalent.  No idea about flatpak or pip installs.

**Pull request closed without merging**
